### ISSUE TITLE
Incorrect link to issues.

### ISSUE THREAD

**Issue by ssOleg** [kaimanhub/MastodonBot.ex#1]
It seems it was missed accidentally in documentation or some kind of template was used before repo was created. 
I found `https://github.com/your-repo/issues` instead of `https://github.com/kaimanhub/MastodonBot.ex/issues`.
It is not something critical but it is easy to fix.

**Comment by kaimanhub** [comment]
Thank you for pointing this out! It looks like there was indeed a small oversight in the documentation. I appreciate you bringing it to our attention.
