### ISSUE TITLE
Continuation Running tests requires MASTODON_DOMAIN env var 

### ISSUE THREAD

**Issue by knightpp** [kaimanhub/MastodonBot.ex#4]
See #3

**Comment by kaimanhub** [comment]
Issue was patched in the previous PR.
When you have a moment, could you please verify if the fix resolves the problem on your end? And feel free to create more issues if you spot anything else. Thank you!

**Comment by knightpp** [comment]
As I said in #3 the issues is not fixed. If you cannot reproduce it, try starting clean. Alternatively, add CI job.

**Comment by knightpp** [comment]
fixed by force push :scream:
